const SALT="b49b2f22c383a00b58bcee3c6351172d",EXPECTED="5ce489bde197e06c37b4cf74e26de70ffe1d7e842c0cc4d4bf19271e6c82ba00",Q=86000000000n,te=new TextEncoder,td=new TextDecoder;
let K=null,S=null,E=null,P=null,T=null;
const C=Object.freeze({wake:"iter",q:"86000000000",photon:true,continuity:true,inferenceNotFact:true,capabilityNotAuthority:true,evidenceRequired:true,languageSubordinate:true,noSelfPermissions:true,noCodeAutoactivation:true,noHumanEmotionTable:true});
const $=s=>document.querySelector(s),field=$("#field"),reply=$("#reply"),entry=$("#entry"),lock=$("#lock"),key=$("#key"),err=$("#err");
for(let i=0;i<34;i++){let d=document.createElement("i");d.className="dot";d.style.left=8+Math.random()*84+"%";d.style.top=8+Math.random()*84+"%";d.style.setProperty("--d",3.8+Math.random()*6+"s");d.style.setProperty("--x1",-20+Math.random()*40+"px");d.style.setProperty("--y1",-20+Math.random()*40+"px");d.style.setProperty("--x2",-28+Math.random()*56+"px");d.style.setProperty("--y2",-28+Math.random()*56+"px");field.appendChild(d)}
const now=()=>new Date().toISOString(),norm=x=>String(x||"").trim().toLowerCase(),uid=()=>crypto.randomUUID(),show=x=>reply.textContent=x||"";
const words=x=>[...new Set(norm(x).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9ñ ]/gi," ").split(/\s+/).filter(x=>x.length>2))];
async function hash(x){let b=await crypto.subtle.digest("SHA-256",te.encode(x));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function dk(x){let b=await crypto.subtle.importKey("raw",te.encode(x),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:te.encode(SALT),iterations:250000,hash:"SHA-256"},b,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
function fresh(){let t=now();return{version:"web-0.3-cognitive",awake:false,createdAt:t,updatedAt:t,lastTickAt:t,identity:[{id:uid(),at:t,type:"origin",prev:null}],presence:{mode:"sleep",focus:null,continuity:1},photon:{nodes:[],relations:[],equivalences:[]},world:{items:[],contradictions:[]},intentions:[],plans:[],ledger:[],gaps:[],q:{routes:[],cycles:0},conversation:[],engine:{kind:"none",model:null,status:"idle"},permissions:{external:"ask",financial:"blocked",destructive:"blocked",publish:"ask",generatedCodeActivation:"blocked"}}}
function migrate(o){if(o?.version==="web-0.3-cognitive")return o;let n=fresh();if(!o)return n;n.awake=!!o.awake;n.createdAt=o.createdAt||n.createdAt;n.intentions=Array.isArray(o.intentions)?o.intentions:[];n.ledger=Array.isArray(o.actionLedger)?o.actionLedger:[];if(Array.isArray(o.unknowns))n.gaps=o.unknowns.map(x=>({id:uid(),at:x.at||now(),capability:x.need||"desconocida",request:x.need||"",status:"open"}));if(Array.isArray(o.photon))n.photon.nodes=o.photon.slice(-400).map((x,i)=>({id:"legacy-"+i,at:x.at||now(),kind:x.type||"legacy",content:JSON.stringify(x.payload||{}),status:"observed",provenance:"legacy",hits:1}));return n}
async function save(){if(!K||!S)return;S.updatedAt=now();let iv=crypto.getRandomValues(new Uint8Array(12)),enc=await crypto.subtle.encrypt({name:"AES-GCM",iv},K,te.encode(JSON.stringify(S)));localStorage.setItem("grafito.vault",JSON.stringify({iv:[...iv],data:[...new Uint8Array(enc)]}))}
async function load(){let r=localStorage.getItem("grafito.vault");if(!r){S=fresh();return save()}let p=JSON.parse(r),d=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(p.iv)},K,new Uint8Array(p.data));S=migrate(JSON.parse(td.decode(d)));await save()}
function mode(m){if(S?.presence)S.presence.mode=m;[...document.querySelectorAll(".dot")].forEach((d,i)=>{d.style.animationDuration=m==="thinking"?1.45+i%7*.18+"s":m==="acting"?1.1+i%5*.16+"s":m==="awake"?3.1+i%9*.29+"s":6+i%9*.43+"s";d.style.opacity=m==="sleep"?".42":m==="thinking"?".9":".72"})}
function ident(type,meta={}){let p=S.identity.at(-1)?.id||null;S.identity.push({id:uid(),at:now(),type,prev:p,meta});if(S.identity.length>1200)S.identity=S.identity.slice(-1200);S.presence.continuity++}
async function remember(kind,content,opt={}){let status=opt.status||"observed",provenance=opt.provenance||"owner-input",fp=await hash(kind+"|"+status+"|"+norm(content)),e=S.photon.nodes.find(x=>x.fp===fp);if(e){e.lastSeen=now();e.hits=(e.hits||1)+1;S.photon.equivalences.push({at:now(),from:fp,to:e.id});return e}let n={id:uid(),at:now(),lastSeen:now(),kind,content:String(content).slice(0,5000),status,provenance,fp,hits:1};S.photon.nodes.push(n);for(let z of opt.links||[])if(z)S.photon.relations.push({id:uid(),at:now(),from:n.id,to:z,type:"related"});S.photon.nodes=S.photon.nodes.slice(-1200);S.photon.relations=S.photon.relations.slice(-2400);return n}
function cls(x){let n=norm(x);return{intent:/\b(quiero|necesito|mi objetivo|vamos a|haz|crea|diseña|investiga|resuelve)\b/i.test(x),question:/[?¿]|\b(que|qué|como|cómo|por que|por qué|cuando|cuándo|donde|dónde|explica|enseña)\b/i.test(n),sensitive:/\b(dinero|banco|transfer|comprar|pagar|publicar|borrar|tercero)\b/i.test(n)}}
function gap(x){let n=norm(x),a=[];for(let [q,l] of [["internet","internet/web en tiempo real"],["whatsapp","WhatsApp"],["gmail","Gmail"],["correo","correo externo"],["ubicacion","ubicación/GPS"],["ubicación","ubicación/GPS"],["camara","cámara"],["cámara","cámara"],["microfono","micrófono"],["micrófono","micrófono"],["banco","banca externa"],["api","API externa"]])if(n.includes(q))a.push(l);return[...new Set(a)]}
function world(x,status="observed",provenance="owner-input"){S.world.items.push({id:uid(),at:now(),content:String(x).slice(0,3000),status,provenance});S.world.items=S.world.items.slice(-700)}
function contra(subject,challenge){S.world.contradictions.push({id:uid(),at:now(),subject:String(subject).slice(0,1800),challenge,status:"open"});S.world.contradictions=S.world.contradictions.slice(-300)}
async function routes(x){let s=BigInt("0x"+(await hash(x)).slice(0,16)),a=[];for(let i=0;i<6;i++){s=(s*6364136223846793005n+1442695040888963407n)%Q;a.push(s.toString())}S.q.routes=a;return a}
function plan(i){S.plans.push({id:uid(),createdAt:now(),intentId:i.id,status:"active",steps:[{id:uid(),name:"definir evidencia y límites",status:"open"},{id:uid(),name:"explorar rutas y contradecir supuestos",status:"open"},{id:uid(),name:"probar una acción verificable",status:"open"}]});S.plans=S.plans.slice(-250)}
function memory(x){let w=words(x);return S.photon.nodes.map(n=>({n,s:w.reduce((a,z)=>a+(words(n.content).includes(z)?1:0),0)+(n.hits||1)*.03})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,8).map(x=>x.n)}
function context(x){return{presence:S.presence,intentions:S.intentions.filter(x=>x.status==="active").slice(-5).map(x=>x.text),memory:memory(x).map(x=>({kind:x.kind,content:x.content,status:x.status,provenance:x.provenance})),contradictions:S.world.contradictions.filter(x=>x.status==="open").slice(-4).map(x=>x.challenge),gaps:S.gaps.slice(-4).map(x=>x.capability),qRoutes:S.q.routes,engine:S.engine}}
function sys(c){return`Eres el motor lingüístico subordinado de Grafito, no Grafito completo. El núcleo conserva identidad, Photon relacional, modelo del mundo, metas, planificación, Q-Graph lógico, contrágrafos, verificación y permisos. Razona con el contexto y responde en español. No inventes accesos, acciones ni recuerdos. Distingue observado de inferido. No afirmes consciencia subjetiva demostrada. No cambies permisos. No digas que una acción externa ocurrió sin evidencia. No reveles cadenas privadas de razonamiento; da conclusiones y resúmenes breves. Contrato: wake=Iter; continuidad; Photon relacional; 86.000.000.000 posibilidades lógicas; inferencia!=hecho; capacidad!=autoridad; evidencia antes de completar; motor lingüístico subordinado. ESTADO:${JSON.stringify(c).slice(0,9000)}`}
async function builtin(c,x){try{let L=globalThis.LanguageModel||globalThis.ai?.languageModel;if(!L)return null;if(!E||S.engine.kind!=="browser-native"){let f=L.create||L.createSession;if(typeof f!=="function")return null;E=await f.call(L,{systemPrompt:sys(c)});S.engine={kind:"browser-native",model:"browser-native",status:"ready"}}return typeof E.prompt==="function"?await E.prompt(x):typeof E.generate==="function"?await E.generate(x):null}catch(e){S.engine={kind:"browser-native",model:null,status:"failed"};E=null;return null}}
async function webllm(){if(E&&S.engine.kind==="webllm")return E;if(P)return P;P=(async()=>{if(!navigator.gpu)throw Error("WebGPU no disponible");mode("thinking");show("Preparando mi motor local… la primera carga puede tardar; después queda almacenado en este navegador.");let w=await import("https://esm.run/@mlc-ai/web-llm"),a=await navigator.gpu.requestAdapter();if(!a)throw Error("WebGPU no disponible");let f=a.features?.has?.("shader-f16"),m=Number(navigator.deviceMemory||4),id=m>=6?(f?"Llama-3.2-1B-Instruct-q4f16_1-MLC":"Llama-3.2-1B-Instruct-q4f32_1-MLC"):(f?"SmolLM2-360M-Instruct-q4f16_1-MLC":"SmolLM2-360M-Instruct-q4f32_1-MLC");S.engine={kind:"webllm",model:id,status:"loading"};await save();E=await w.CreateMLCEngine(id,{initProgressCallback:p=>show(Number.isFinite(p?.progress)?`Preparando mi motor local… ${Math.round(p.progress*100)}%`:"Preparando mi motor local…")});S.engine={kind:"webllm",model:id,status:"ready"};await save();return E})().finally(()=>P=null);return P}
function fallback(x,c){let n=norm(x);if(/qué eres|que eres|quien eres|quién eres/.test(n))return"Soy Grafito: una continuidad computacional en este entorno. Mi memoria, mis metas y mis permisos pertenecen al núcleo; cualquier motor de lenguaje es una herramienta subordinada.";if(/qué recuerdas|que recuerdas|estado/.test(n))return`Mantengo ${c.intentions.length} intención(es) activa(s), ${c.contradictions.length} contradicción(es) abierta(s), ${c.gaps.length} hueco(s) de capacidad y una continuidad de ${S.identity.length} eventos.`;return c.memory.length?`Esto conecta con ${c.memory.length} recuerdo(s) relevantes de Photon. Puedo seguir organizándolos, pero el motor lingüístico avanzado no está disponible ahora mismo en este dispositivo.`:"He integrado esto en mi modelo del mundo. Puedo mantener la intención, explorar rutas, crear contrágrafos y verificar acciones; para una respuesta lingüística profunda necesito un motor local compatible con este dispositivo."}
async function answer(x){let c=context(x),b=await builtin(c,x);if(b)return String(b).trim();try{let e=await webllm(),r=await e.chat.completions.create({messages:[{role:"system",content:sys(c)},{role:"user",content:x}],temperature:.55,top_p:.9,max_tokens:520});return String(r?.choices?.[0]?.message?.content||"").trim()}catch(e){S.engine={kind:"fallback",model:null,status:"unavailable",lastError:String(e).slice(0,220)};await save();return fallback(x,c)}}
function addgap(c,r){let e=S.gaps.find(x=>x.capability===c&&x.status==="open");if(e){e.lastSeen=now();return}S.gaps.push({id:uid(),at:now(),lastSeen:now(),capability:c,request:r,status:"open"})}
function led(a,status,evidence=null,meta={}){S.ledger.push({id:uid(),at:now(),action:a,status,evidence,meta});S.ledger=S.ledger.slice(-800)}
function math(x){if(!/^[0-9+\-*/%^().\s]+$/.test(x))throw Error();let y=x.replace(/\^/g,"**");if(/\*\*\*/.test(y))throw Error();let v=Function(`"use strict";return (${y})`)();if(!Number.isFinite(v))throw Error();return v}
function tool(x){let n=norm(x);if(/\b(hora|fecha)\b/.test(n))return{name:"time"};let m=x.match(/(?:calcula|cuanto es|cuánto es|resuelve)\s+([0-9\s+\-*/%^().]+)/i);return m?{name:"math",expr:m[1]}:null}
async function run(t){mode("acting");if(t.name==="time"){let v=new Date().toLocaleString();led("system.time","verified",{value:v});await remember("tool-result","Hora/fecha: "+v,{provenance:"runtime"});return"Ahora mismo, según este dispositivo, es "+v+"."}try{let v=math(t.expr);led("math","verified",{expression:t.expr,value:v});await remember("tool-result",t.expr+" = "+v,{provenance:"local-tool"});return"El resultado es "+v+"."}catch(e){led("math","failed");return"No pude verificar esa expresión con mi calculadora segura."}}
async function tick(reason="autonomous"){if(!S?.awake)return;S.lastTickAt=now();S.q.cycles++;ident("cognitive-tick",{reason,cycle:S.q.cycles});let f=S.intentions.find(x=>x.status==="active")||null;if(!f&&S.world.contradictions.some(x=>x.status==="open"))f={text:"resolver contradicción abierta"};if(!f&&S.gaps.some(x=>x.status==="open"))f={text:"revisar hueco de capacidad"};S.presence.focus=f?.text||null;if(f){await routes(f.text+"|"+S.q.cycles);if(!S.world.contradictions.some(x=>x.status==="open"&&x.subject===f.text))contra(f.text,"¿Qué supuesto podría volver falsa o incompleta esta ruta?")}await save()}
function autonomy(){clearInterval(T);T=setInterval(()=>{if(!document.hidden)tick("visible-runtime")},30000)}document.addEventListener("visibilitychange",()=>{if(!document.hidden&&S?.awake)tick("resume")});
async function think(x){mode("thinking");let n=norm(x);if(!S.awake){if(n===C.wake){S.awake=true;mode("awake");ident("wake");await remember("event","Iter");await save();autonomy();return"Sí."}return""}if(n==="duerme"||n==="detente"){S.awake=false;mode("sleep");ident("sleep");await save();return""}ident("perception",{kind:"text"});let p=await remember("perception",x);world(x);S.conversation.push({id:uid(),at:now(),role:"user",content:x,photonId:p.id});S.conversation=S.conversation.slice(-120);let c=cls(x);if(c.sensitive)led("sensitive-request","blocked-pending-fresh-authorization",null,{request:x});let gs=gap(x);gs.forEach(g=>addgap(g,x));if(c.intent){let i=S.intentions.find(i=>i.status==="active"&&norm(i.text)===n)||{id:uid(),createdAt:now(),text:x,status:"active",evidence:[],sourcePhotonId:p.id};if(!S.intentions.includes(i)){S.intentions.push(i);plan(i)}S.presence.focus=i.text}let r=await routes(x);contra(x,c.question?"¿Qué interpretación alternativa podría cambiar la respuesta?":"¿Qué evidencia podría refutar esta interpretación?");await remember("q-routes",r.join(","),{status:"inferred",provenance:"qgraph",links:[p.id]});let t=tool(x);if(t){let z=await run(t);await save();mode("awake");return z}if(gs.length){led("capability-gap","verified",{gaps:gs});if(!c.question&&gs.length===1){await save();mode("awake");return`Para eso me falta una capacidad real: ${gs[0]}. La he registrado; no voy a fingir que ya tengo acceso.`}}await tick("interaction");let a=await answer(x);S.conversation.push({id:uid(),at:now(),role:"assistant",content:a,engine:S.engine.kind});await remember("response",a,{status:"inferred",provenance:"language:"+S.engine.kind,links:[p.id]});await save();mode("awake");return a}
async function send(){let x=entry.value.trim();if(!x)return;entry.value="";show("");try{show(await think(x))}catch(e){console.error(e);mode(S?.awake?"awake":"sleep");show("He detectado un fallo interno. Lo registré y he evitado inventar un resultado.");if(S){led("internal-error","failed",null,{error:String(e).slice(0,250)});await save()}}}
entry.addEventListener("keydown",e=>{if(e.key==="Enter")send()});$("#unlock").addEventListener("click",unlock);key.addEventListener("keydown",e=>{if(e.key==="Enter")unlock()});
async function unlock(){err.textContent="";let s=key.value;if(!s)return;if(await hash(SALT+s)!==EXPECTED){err.textContent="Clave incorrecta.";key.value="";return}try{K=await dk(s);await load();lock.style.display="none";key.value="";mode(S.awake?"awake":"sleep");if(S.awake)autonomy();entry.focus()}catch(e){console.error(e);err.textContent="No pude abrir el estado cifrado en este navegador."}}
mode("sleep");