(() => {
const SALT = "b49b2f22c383a00b58bcee3c6351172d";
const EXPECTED = "a841a178c7a43a4685affe7b83e73542d9941d37219a6987f5c4de3722b313e3";
const te = new TextEncoder(), td = new TextDecoder();
let vaultKey = null, state = null;
const field=document.querySelector('#field'),reply=document.querySelector('#reply'),entry=document.querySelector('#entry'),lock=document.querySelector('#lock'),keyInput=document.querySelector('#key'),err=document.querySelector('#err');
for(let i=0;i<34;i++){const d=document.createElement('i');d.className='dot';d.style.left=(8+Math.random()*84)+'%';d.style.top=(8+Math.random()*84)+'%';d.style.setProperty('--d',(3.8+Math.random()*6)+'s');d.style.setProperty('--x1',(-20+Math.random()*40)+'px');d.style.setProperty('--y1',(-20+Math.random()*40)+'px');d.style.setProperty('--x2',(-28+Math.random()*56)+'px');d.style.setProperty('--y2',(-28+Math.random()*56)+'px');field.appendChild(d);}
async function sha256Hex(s){const b=await crypto.subtle.digest('SHA-256',te.encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function deriveKey(secret){const base=await crypto.subtle.importKey('raw',te.encode(secret),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:te.encode(SALT),iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
function freshState(){const now=new Date().toISOString();return{version:'web-0.1',awake:false,createdAt:now,updatedAt:now,identityThread:[{at:now,type:'origin',prev:null}],photon:[],intentions:[],unknowns:[],contradictions:[],actionLedger:[],cycles:0};}
async function save(){if(!vaultKey||!state)return;state.updatedAt=new Date().toISOString();const iv=crypto.getRandomValues(new Uint8Array(12));const enc=await crypto.subtle.encrypt({name:'AES-GCM',iv},vaultKey,te.encode(JSON.stringify(state)));localStorage.setItem('grafito.vault',JSON.stringify({iv:[...iv],data:[...new Uint8Array(enc)]}));}
async function load(){const raw=localStorage.getItem('grafito.vault');if(!raw){state=freshState();await save();return}const pack=JSON.parse(raw);const dec=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(pack.iv)},vaultKey,new Uint8Array(pack.data));state=JSON.parse(td.decode(dec));}
function record(type,payload={}){const at=new Date().toISOString();const prev=state.identityThread.length?state.identityThread[state.identityThread.length-1].at:null;state.identityThread.push({at,type,prev});state.photon.push({at,type,payload});if(state.photon.length>600)state.photon=state.photon.slice(-600);}
function setMode(mode){[...document.querySelectorAll('.dot')].forEach((d,i)=>{d.style.animationDuration=mode==='thinking'?(1.6+(i%7)*.22)+'s':mode==='awake'?(3.2+(i%9)*.31)+'s':(6+(i%9)*.43)+'s';});}
function norm(s){return s.trim().toLowerCase()}
function isIntent(s){return /\b(quiero|necesito|mi objetivo|vamos a|quiero construir|quiero crear|quiero conseguir)\b/i.test(s)}
function gap(s){return /whatsapp|correo|gmail|internet|web|ubicaci[oó]n|gps|c[aá]mara|microfono|micrófono|api|banco|cuenta externa/i.test(s)}
async function think(text){setMode('thinking');await new Promise(r=>setTimeout(r,260+Math.random()*420));const n=norm(text);if(!state.awake){if(n==='iter'){state.awake=true;record('wake',{source:'text'});await save();setMode('awake');return'Sí.'}return''}if(n==='duerme'||n==='detente'){state.awake=false;record('sleep');await save();setMode('sleep');return''}record('perception',{kind:'text',content:text,provenance:'owner-input',status:'observed'});if(gap(text)){state.unknowns.push({at:new Date().toISOString(),need:text,status:'capability_gap'});record('capability_gap',{request:text});await save();setMode('awake');return'Esa capacidad necesita un conector o permiso real que este runtime web todavía no tiene. La registro como capacidad pendiente; no voy a fingir acceso.'}if(isIntent(text)){const intent={id:crypto.randomUUID(),createdAt:new Date().toISOString(),text,status:'active',evidence:[]};state.intentions.push(intent);record('intention',intent);await save();setMode('awake');return'Lo mantengo como una intención activa. No la daré por cumplida sin evidencia.'}if(/qué eres|que eres|quien eres|quién eres/i.test(text)){setMode('awake');return'Soy Grafito: una continuidad computacional persistente en este entorno. Distingo lo observado, lo inferido y lo que todavía no puedo comprobar.'}if(/estado|qué recuerdas|que recuerdas/i.test(text)){setMode('awake');return`Mantengo ${state.intentions.filter(x=>x.status==='active').length} intención(es) activa(s), ${state.unknowns.length} hueco(s) de capacidad y una línea de continuidad de ${state.identityThread.length} eventos.`}if(/contin[uú]a|piensa|explora/i.test(text)){state.cycles++;record('cognitive_cycle',{cycle:state.cycles,focus:state.intentions.at(-1)?.text||text});await save();setMode('awake');return state.intentions.length?'He realizado otro ciclo sobre la intención activa: revisar supuestos, buscar contradicciones y separar lo que sé de lo que falta comprobar.':'He realizado un ciclo interno, pero no voy a inventar una meta que no me hayas dado.'}record('conversation',{content:text,status:'observed'});await save();setMode('awake');return'Lo incorporé a mi estado. Si esto implica una meta, una contradicción o una acción verificable, la mantendré separada de una simple conversación.'}
async function send(){const text=entry.value.trim();if(!text)return;entry.value='';reply.textContent='';reply.textContent=await think(text)}
entry.addEventListener('keydown',e=>{if(e.key==='Enter')send()});document.querySelector('#unlock').addEventListener('click',unlock);keyInput.addEventListener('keydown',e=>{if(e.key==='Enter')unlock()});
async function unlock(){err.textContent='';const secret=keyInput.value;if(!secret)return;const got=await sha256Hex(SALT+secret);if(got!==EXPECTED){err.textContent='Clave incorrecta.';keyInput.value='';return}try{vaultKey=await deriveKey(secret);await load();lock.style.display='none';keyInput.value='';setMode(state.awake?'awake':'sleep');entry.focus()}catch(e){err.textContent='No pude abrir el estado cifrado en este navegador.'}}
setMode('sleep');
})();