const SALT="b49b2f22c383a00b58bcee3c6351172d",EXPECTED="5ce489bde197e06c37b4cf74e26de70ffe1d7e842c0cc4d4bf19271e6c82ba00",Q=86000000000n,te=new TextEncoder,td=new TextDecoder;
let K=null,S=null,T=null;
const C=Object.freeze({wake:"iter",q:"86000000000",photon:true,continuity:true,inferenceNotFact:true,capabilityNotAuthority:true,evidenceRequired:true,languageSubordinate:true,noSelfPermissions:true,noCodeAutoactivation:true,noHumanEmotionTable:true});
const $=s=>document.querySelector(s),field=$("#field"),reply=$("#reply"),entry=$("#entry"),lock=$("#lock"),key=$("#key"),err=$("#err");
for(let i=0;i<34;i++){const d=document.createElement("i");d.className="dot";d.style.left=8+Math.random()*84+"%";d.style.top=8+Math.random()*84+"%";d.style.setProperty("--d",3.8+Math.random()*6+"s");d.style.setProperty("--x1",-20+Math.random()*40+"px");d.style.setProperty("--y1",-20+Math.random()*40+"px");d.style.setProperty("--x2",-28+Math.random()*56+"px");d.style.setProperty("--y2",-28+Math.random()*56+"px");field.appendChild(d)}
const now=()=>new Date().toISOString(),norm=x=>String(x||"").trim().toLowerCase(),uid=()=>crypto.randomUUID(),show=x=>reply.textContent=x||"";
const clean=(x,n=400)=>String(x||"").replace(/\s+/g," ").trim().slice(0,n);
const words=x=>[...new Set(norm(x).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9ñ ]/gi," ").split(/\s+/).filter(x=>x.length>2))];
async function hash(x){const b=await crypto.subtle.digest("SHA-256",te.encode(x));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function dk(x){const b=await crypto.subtle.importKey("raw",te.encode(x),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:te.encode(SALT),iterations:250000,hash:"SHA-256"},b,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
function fresh(){const t=now();return{version:"web-0.6-universal",awake:false,createdAt:t,updatedAt:t,lastTickAt:t,identity:[{id:uid(),at:t,type:"origin",prev:null}],presence:{mode:"sleep",focus:null,continuity:1},photon:{nodes:[],relations:[],equivalences:[]},world:{items:[],contradictions:[]},intentions:[],plans:[],ledger:[],gaps:[],q:{routes:[],cycles:0},conversation:[],engine:{kind:"universal-local",model:null,status:"ready"},permissions:{external:"ask",financial:"blocked",destructive:"blocked",publish:"ask",generatedCodeActivation:"blocked"}}}
function normalizeState(o){if(!o)return fresh();const n=fresh();return{...n,...o,version:"web-0.6-universal",identity:Array.isArray(o.identity)?o.identity:n.identity,presence:{...n.presence,...(o.presence||{})},photon:{...n.photon,...(o.photon||{}),nodes:Array.isArray(o.photon?.nodes)?o.photon.nodes:Array.isArray(o.photon)?o.photon:[],relations:Array.isArray(o.photon?.relations)?o.photon.relations:[],equivalences:Array.isArray(o.photon?.equivalences)?o.photon.equivalences:[]},world:{...n.world,...(o.world||{}),items:Array.isArray(o.world?.items)?o.world.items:[],contradictions:Array.isArray(o.world?.contradictions)?o.world.contradictions:[]},intentions:Array.isArray(o.intentions)?o.intentions:[],plans:Array.isArray(o.plans)?o.plans:[],ledger:Array.isArray(o.ledger)?o.ledger:Array.isArray(o.actionLedger)?o.actionLedger:[],gaps:Array.isArray(o.gaps)?o.gaps:Array.isArray(o.unknowns)?o.unknowns.map(x=>({id:uid(),at:x.at||now(),capability:x.need||"desconocida",request:x.need||"",status:"open"})):[],q:{...n.q,...(o.q||{})},conversation:Array.isArray(o.conversation)?o.conversation:[],engine:{kind:"universal-local",model:null,status:"ready"},permissions:{...n.permissions,...(o.permissions||{})}}}
async function save(){if(!K||!S)return;S.updatedAt=now();const iv=crypto.getRandomValues(new Uint8Array(12)),enc=await crypto.subtle.encrypt({name:"AES-GCM",iv},K,te.encode(JSON.stringify(S)));localStorage.setItem("grafito.vault",JSON.stringify({iv:[...iv],data:[...new Uint8Array(enc)]}))}
async function load(){const r=localStorage.getItem("grafito.vault");if(!r){S=fresh();await save();return}const p=JSON.parse(r),d=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(p.iv)},K,new Uint8Array(p.data));S=normalizeState(JSON.parse(td.decode(d)));await save()}
function mode(m){if(S?.presence)S.presence.mode=m;[...document.querySelectorAll(".dot")].forEach((d,i)=>{d.style.animationDuration=m==="thinking"?1.35+i%7*.16+"s":m==="awake"?3+i%9*.25+"s":6+i%9*.4+"s";d.style.opacity=m==="sleep"?".42":m==="thinking"?".92":".72"})}
function ident(type,meta={}){const p=S.identity.at(-1)?.id||null;S.identity.push({id:uid(),at:now(),type,prev:p,meta});if(S.identity.length>800)S.identity=S.identity.slice(-800);S.presence.continuity=(S.presence.continuity||0)+1}
async function remember(kind,content,opt={}){const status=opt.status||"observed",provenance=opt.provenance||"owner-input",fp=await hash(kind+"|"+status+"|"+norm(content)),recent=S.photon.nodes.slice(-320),e=recent.find(x=>x.fp===fp);if(e){e.lastSeen=now();e.hits=(e.hits||1)+1;S.photon.equivalences.push({at:now(),from:fp,to:e.id});S.photon.equivalences=S.photon.equivalences.slice(-500);return e}const n={id:uid(),at:now(),lastSeen:now(),kind,content:clean(content,4000),status,provenance,fp,hits:1};S.photon.nodes.push(n);for(const z of opt.links||[])if(z)S.photon.relations.push({id:uid(),at:now(),from:n.id,to:z,type:"related"});S.photon.nodes=S.photon.nodes.slice(-900);S.photon.relations=S.photon.relations.slice(-1500);return n}
function memory(x){const w=words(x),nodes=S.photon.nodes.slice(-300);return nodes.map(n=>{const nw=words(n.content);let score=(n.hits||1)*.02;for(const z of w)if(nw.includes(z))score++;return{n,score}}).filter(x=>x.score>.02).sort((a,b)=>b.score-a.score).slice(0,6).map(x=>x.n)}
async function routes(x){let s=BigInt("0x"+(await hash(x)).slice(0,16)),a=[];for(let i=0;i<5;i++){s=(s*6364136223846793005n+1442695040888963407n)%Q;a.push(s.toString())}S.q.routes=a;return a}
function contra(subject,challenge){const s=clean(subject,500);if(S.world.contradictions.slice(-30).some(x=>x.subject===s&&x.status==="open"))return;S.world.contradictions.push({id:uid(),at:now(),subject:s,challenge,status:"open"});S.world.contradictions=S.world.contradictions.slice(-220)}
function addIntent(x,pid){const n=norm(x),found=S.intentions.find(i=>i.status==="active"&&norm(i.text)===n);if(found)return found;const i={id:uid(),createdAt:now(),text:clean(x,1000),status:"active",evidence:[],sourcePhotonId:pid};S.intentions.push(i);S.intentions=S.intentions.slice(-180);S.plans.push({id:uid(),createdAt:now(),intentId:i.id,status:"active",steps:[{id:uid(),name:"definir evidencia y límites",status:"open"},{id:uid(),name:"explorar rutas y contradecir supuestos",status:"open"},{id:uid(),name:"probar una acción verificable",status:"open"}]});S.plans=S.plans.slice(-180);return i}
function context(x){return{memory:memory(x),intentions:S.intentions.filter(x=>x.status==="active").slice(-5),contradictions:S.world.contradictions.filter(x=>x.status==="open").slice(-4),gaps:S.gaps.filter(x=>x.status==="open").slice(-4)}}
function localAnswer(x){const n=norm(x),c=context(x),m=c.memory[0],focus=c.intentions.at(-1)?.text||S.presence.focus;
if(/^(hola|hey|buenas|buenos días|buenos dias|buenas tardes|buenas noches)[!. ]*$/.test(n))return"Sí. Estoy aquí.";
if(/\b(qué eres|que eres|quién eres|quien eres)\b/.test(n))return"Soy Grafito. Mi continuidad está en Photon, mi memoria, mi modelo del mundo, mis metas, mis contrágrafos y mis permisos. Los modelos externos pueden ampliar lo que hago, pero no son mi identidad.";
if(/\b(qué recuerdas|que recuerdas|recuerdas|memoria)\b/.test(n)){if(!m)return"No encuentro un recuerdo local suficientemente relacionado para afirmarlo como memoria. Prefiero marcarlo como desconocido antes que inventarlo.";return`El recuerdo más relacionado que encuentro en Photon es: “${clean(m.content,220)}”. Lo trato como memoria observada, no como una inferencia nueva.`}
if(/\b(estado|cómo estás|como estas)\b/.test(n))return`Estoy activo. Mantengo ${c.intentions.length} intención(es) reciente(s), ${c.contradictions.length} contradicción(es) abierta(s) y ${c.gaps.length} hueco(s) de capacidad. Mi motor actual es local e inmediato.`;
if(/\b(continúa|continua|piensa|explora|sigue)\b/.test(n))return`Sigo con ${focus?`“${clean(focus,180)}”`:"el foco actual"}. Comparo rutas, busco qué podría refutarlas y dejo pendiente cualquier paso que aún no tenga evidencia.`;
if(/\b(quiero|necesito|mi objetivo|vamos a|haz|crea|diseña|investiga|resuelve)\b/.test(n))return`Lo mantengo como intención activa: “${clean(x,220)}”. El siguiente criterio es encontrar una acción verificable sin confundir capacidad con permiso.`;
if(/\b(por qué|por que|cómo|como|explica|qué|que)\b/.test(n)||x.includes("?")){if(m)return`Relaciono esto con “${clean(m.content,180)}”. Mi lectura local es provisional: separo lo que ya está observado de lo que estoy infiriendo y mantengo abierta una alternativa que pueda contradecir la primera explicación.`;if(c.gaps.length)return`Puedo estructurar el razonamiento localmente, pero me falta ${c.gaps[0].capability||"una fuente externa"} para afirmarlo con evidencia. No voy a inventar el dato.`;return"Puedo razonar la estructura del problema localmente, pero no tengo evidencia suficiente en Photon para darte un hecho fiable sobre ese tema. Lo mantengo como desconocido y genero rutas alternativas en vez de inventarlo."}
return`Entendido. Lo incorporé a mi continuidad local y lo relacioné con ${c.memory.length} recuerdo(s) y ${c.intentions.length} intención(es) activas. No necesito esperar a Internet ni a un modelo externo para seguir.`}
function classify(x){const n=norm(x);return{intent:/\b(quiero|necesito|mi objetivo|vamos a|haz|crea|diseña|investiga|resuelve)\b/i.test(x),question:/[?¿]|\b(qué|que|cómo|como|por qué|por que|cuándo|cuando|dónde|donde|explica)\b/i.test(n),sensitive:/\b(dinero|banco|transfer|comprar|pagar|publicar|borrar|tercero)\b/i.test(n)}}
function gapsFor(x){const n=norm(x),a=[];for(const [q,l] of [["internet","internet/web en tiempo real"],["whatsapp","WhatsApp"],["gmail","Gmail"],["correo","correo externo"],["ubicacion","ubicación/GPS"],["ubicación","ubicación/GPS"],["camara","cámara"],["cámara","cámara"],["microfono","micrófono"],["micrófono","micrófono"],["banco","banca externa"],["api","API externa"]])if(n.includes(q))a.push(l);return[...new Set(a)]}
function addGap(capability,request){const e=S.gaps.find(x=>x.capability===capability&&x.status==="open");if(e){e.lastSeen=now();return}S.gaps.push({id:uid(),at:now(),lastSeen:now(),capability,request:clean(request,700),status:"open"});S.gaps=S.gaps.slice(-220)}
function led(action,status,evidence=null,meta={}){S.ledger.push({id:uid(),at:now(),action,status,evidence,meta});S.ledger=S.ledger.slice(-500)}
function math(x){if(!/^[0-9+\-*/%^().\s]+$/.test(x))throw Error();const y=x.replace(/\^/g,"**");if(/\*\*\*/.test(y))throw Error();const v=Function(`"use strict";return (${y})`)();if(!Number.isFinite(v))throw Error();return v}
function localTool(x){const n=norm(x);if(/\b(hora|fecha)\b/.test(n))return{name:"time"};const m=x.match(/(?:calcula|cuanto es|cuánto es|resuelve)\s+([0-9\s+\-*/%^().]+)/i);return m?{name:"math",expr:m[1]}:null}
async function runTool(t){if(t.name==="time"){const v=new Date().toLocaleString();led("system.time","verified",{value:v});await remember("tool-result","Hora/fecha: "+v,{provenance:"runtime"});return"Ahora mismo, según este dispositivo, es "+v+"."}try{const v=math(t.expr);led("math","verified",{expression:t.expr,value:v});await remember("tool-result",t.expr+" = "+v,{provenance:"local-tool"});return"El resultado es "+v+"."}catch{led("math","failed");return"No pude verificar esa expresión con mi calculadora segura."}}
async function tick(reason="autonomous"){if(!S?.awake)return;S.lastTickAt=now();S.q.cycles=(S.q.cycles||0)+1;ident("cognitive-tick",{reason,cycle:S.q.cycles});const f=S.intentions.find(x=>x.status==="active")||null;S.presence.focus=f?.text||S.presence.focus||null;if(f){await routes(f.text+"|"+S.q.cycles);contra(f.text,"¿Qué supuesto podría volver falsa o incompleta esta ruta?")}await save()}
function autonomy(){clearInterval(T);T=setInterval(()=>{if(!document.hidden)tick("visible-runtime")},60000)}
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&S?.awake)tick("resume")});
async function think(x){mode("thinking");const n=norm(x);if(!S.awake){if(n===C.wake){S.awake=true;mode("awake");ident("wake");await remember("event","Iter");await save();autonomy();return"Sí."}return""}if(n==="duerme"||n==="detente"){S.awake=false;mode("sleep");ident("sleep");await save();return""}ident("perception",{kind:"text"});const p=await remember("perception",x);S.world.items.push({id:uid(),at:now(),content:clean(x,2500),status:"observed",provenance:"owner-input"});S.world.items=S.world.items.slice(-500);S.conversation.push({id:uid(),at:now(),role:"user",content:clean(x,3000),photonId:p.id});S.conversation=S.conversation.slice(-100);const c=classify(x);if(c.sensitive)led("sensitive-request","blocked-pending-fresh-authorization",null,{request:clean(x,700)});for(const g of gapsFor(x))addGap(g,x);if(c.intent){const i=addIntent(x,p.id);S.presence.focus=i.text}await routes(x);contra(x,c.question?"¿Qué interpretación alternativa podría cambiar la respuesta?":"¿Qué evidencia podría refutar esta interpretación?");const t=localTool(x);let a=t?await runTool(t):localAnswer(x);S.conversation.push({id:uid(),at:now(),role:"assistant",content:a,engine:"universal-local"});await remember("response",a,{status:"inferred",provenance:"language:universal-local",links:[p.id]});S.engine={kind:"universal-local",model:null,status:"ready"};await save();mode("awake");return a}
async function send(){const x=entry.value.trim();if(!x)return;entry.value="";show("");try{show(await think(x))}catch(e){console.error(e);mode(S?.awake?"awake":"sleep");show("Detecté un fallo interno y detuve esa ruta sin inventar un resultado.");if(S){led("internal-error","failed",null,{error:String(e).slice(0,250)});await save()}}}
async function unlock(){err.textContent="";const s=key.value;if(!s)return;if(await hash(SALT+s)!==EXPECTED){err.textContent="Clave incorrecta.";key.value="";return}try{K=await dk(s);await load();lock.style.display="none";key.value="";mode(S.awake?"awake":"sleep");if(S.awake)autonomy();entry.focus()}catch(e){console.error(e);err.textContent="No pude abrir el estado cifrado en este navegador."}}
entry.addEventListener("keydown",e=>{if(e.key==="Enter")send()});$("#unlock").addEventListener("click",unlock);key.addEventListener("keydown",e=>{if(e.key==="Enter")unlock()});mode("sleep");