const SALT="b49b2f22c383a00b58bcee3c6351172d";
const EXPECTED="5ce489bde197e06c37b4cf74e26de70ffe1d7e842c0cc4d4bf19271e6c82ba00";
const QMAX=86000000000;
const te=new TextEncoder(),td=new TextDecoder();
let K=null,S=null,T=null,bg=Promise.resolve(),saveTimer=null;
const C=Object.freeze({wake:"iter",q:"86000000000",photon:true,continuity:true,inferenceNotFact:true,capabilityNotAuthority:true,evidenceRequired:true,languageSubordinate:true,noSelfPermissions:true,noCodeAutoactivation:true,noHumanEmotionTable:true,offlineFirst:true,instantVisibleResponse:true,noInternalStructuresVisible:true});
const STOP=new Set("que qué es de del la el los las un una unos unas y o a al en por para con sin sobre como cómo cuando cuándo donde dónde quien quién esto eso esa ese este esta estos estas mi mis tu tus su sus se me te lo le les ya si sí no muy mas más hay ser estar fue son era eres soy he ha han hace hacer puede puedo puedes podria podría cada algo alguien algun algún alguna algunos algunas".split(/\s+/));
const $=s=>document.querySelector(s),field=$("#field"),reply=$("#reply"),entry=$("#entry"),lock=$("#lock"),key=$("#key"),err=$("#err");
const now=()=>new Date().toISOString();
const norm=x=>String(x||"").trim().toLowerCase();
const clean=(x,n=700)=>String(x||"").replace(/\s+/g," ").trim().slice(0,n);
const uid=()=>crypto.randomUUID?crypto.randomUUID():"g-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2);
const show=x=>{reply.textContent=safeVisible(x)};
for(let i=0;i<34;i++){const d=document.createElement("i");d.className="dot";d.style.left=8+Math.random()*84+"%";d.style.top=8+Math.random()*84+"%";d.style.setProperty("--d",3.8+Math.random()*6+"s");d.style.setProperty("--x1",-20+Math.random()*40+"px");d.style.setProperty("--y1",-20+Math.random()*40+"px");d.style.setProperty("--x2",-28+Math.random()*56+"px");d.style.setProperty("--y2",-28+Math.random()*56+"px");field.appendChild(d)}
function mode(m){if(S&&S.presence)S.presence.mode=m;document.querySelectorAll(".dot").forEach((d,i)=>{d.style.animationDuration=m==="thinking"?1.5+i%7*.16+"s":m==="awake"?3.1+i%9*.24+"s":6+i%9*.4+"s";d.style.opacity=m==="sleep"?".42":m==="thinking"?".9":".72"})}
function stripAccents(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function tokens(x){return [...new Set(stripAccents(norm(x)).replace(/[^a-z0-9ñ ]/gi," ").split(/\s+/).filter(z=>z.length>2&&!STOP.has(z)))];}
function unwrap(value,depth=0){if(depth>4||value==null)return"";if(typeof value==="string"){const s=value.trim();if(!s)return"";if((s.startsWith("{")&&s.endsWith("}"))||(s.startsWith("[")&&s.endsWith("]"))){try{return unwrap(JSON.parse(s),depth+1)}catch{return""}}return clean(s,3000)}if(Array.isArray(value)){for(const v of value){const s=unwrap(v,depth+1);if(s)return s}return""}if(typeof value==="object"){for(const k of ["content","text","message","query","value","title","name"]){if(k in value){const s=unwrap(value[k],depth+1);if(s)return s}}if("payload" in value){const s=unwrap(value.payload,depth+1);if(s)return s}return""}return clean(value,3000)}
function safeVisible(value){const s=unwrap(value);if(!s)return"";if((s.startsWith("{")&&s.endsWith("}"))||(s.startsWith("[")&&s.endsWith("]")))return"";return s}
async function hash(x){const b=await crypto.subtle.digest("SHA-256",te.encode(x));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,"0")).join("")}
async function deriveKey(secret){const base=await crypto.subtle.importKey("raw",te.encode(secret),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:te.encode(SALT),iterations:250000,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
function fresh(){const t=now();return{version:"web-0.8-memory-clean",awake:false,createdAt:t,updatedAt:t,lastTickAt:t,identity:[{id:uid(),at:t,type:"origin",prev:null}],presence:{mode:"sleep",focus:null,continuity:1},contract:{version:8,essence:C},photon:{nodes:[],relations:[],equivalences:[]},world:{items:[],contradictions:[]},intentions:[],plans:[],ledger:[],gaps:[],q:{routes:[],cycles:0},conversation:[],engine:{kind:"universal-instant",status:"ready"},permissions:{external:"ask",financial:"blocked",destructive:"blocked",publish:"ask",generatedCodeActivation:"blocked"}}}
function arr(v,f=[]){return Array.isArray(v)?v:f}
function normalizeNode(n){if(!n)return null;const content=unwrap(n.content??n.payload??n.text??n);if(!content)return null;return{...n,id:n.id||uid(),at:n.at||now(),lastSeen:n.lastSeen||n.at||now(),kind:clean(n.kind||n.type||"memory",80),content,status:n.status||"observed",provenance:n.provenance||"legacy",hits:Number(n.hits||1)}}
function normalizeState(o){const n=fresh();if(!o)return n;const p=o.photon||{},w=o.world||{};const rawNodes=arr(p.nodes,Array.isArray(p)?p:[]);const nodes=rawNodes.map(normalizeNode).filter(Boolean).slice(-700);const conv=arr(o.conversation).map(m=>({...m,content:unwrap(m.content)})).filter(m=>m.content).slice(-100);return{...n,...o,version:"web-0.8-memory-clean",identity:arr(o.identity,n.identity).slice(-600),presence:{...n.presence,...(o.presence||{})},contract:{version:8,essence:C},photon:{nodes,relations:arr(p.relations).slice(-1000),equivalences:arr(p.equivalences).slice(-300)},world:{items:arr(w.items).map(i=>({...i,content:unwrap(i.content)})).filter(i=>i.content).slice(-400),contradictions:arr(w.contradictions).slice(-180)},intentions:arr(o.intentions).map(i=>({...i,text:unwrap(i.text||i.content)})).filter(i=>i.text).slice(-160),plans:arr(o.plans).slice(-160),ledger:arr(o.ledger,arr(o.actionLedger)).slice(-400),gaps:arr(o.gaps).slice(-180),q:{...n.q,...(o.q||{})},conversation:conv,engine:{kind:"universal-instant",status:"ready"},permissions:{...n.permissions,...(o.permissions||{})}}}
async function load(){const raw=localStorage.getItem("grafito.vault");if(!raw){S=fresh();return}const p=JSON.parse(raw);const dec=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(p.iv)},K,new Uint8Array(p.data));S=normalizeState(JSON.parse(td.decode(dec)));scheduleSave(20)}
async function save(){if(!K||!S)return;S.updatedAt=now();const iv=crypto.getRandomValues(new Uint8Array(12));const enc=await crypto.subtle.encrypt({name:"AES-GCM",iv},K,te.encode(JSON.stringify(S)));localStorage.setItem("grafito.vault",JSON.stringify({iv:[...iv],data:[...new Uint8Array(enc)]}))}
function scheduleSave(delay=80){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{bg=bg.then(save).catch(()=>{})},delay)}
function ident(type,meta={}){const a=S.identity,prev=a.length?a[a.length-1].id:null;a.push({id:uid(),at:now(),type,prev,meta});if(a.length>600)S.identity=a.slice(-600);S.presence.continuity=(S.presence.continuity||0)+1}
function memory(x){const ws=tokens(x);if(!ws.length)return[];const rank=[];for(const n of S.photon.nodes.slice(-220)){const text=unwrap(n.content);if(!text)continue;const nw=tokens(text);if(!nw.length)continue;let overlap=0;for(const z of ws)if(nw.includes(z))overlap++;if(overlap<1)continue;let score=overlap+(n.hits||1)*.01;if(n.kind==="response")score-=.35;if(norm(text)===norm(x))score-=.25;rank.push({n:{...n,content:text},score})}rank.sort((a,b)=>b.score-a.score);return rank.filter(r=>r.score>.2).slice(0,4).map(r=>r.n)}
function activeIntent(){const a=S.intentions.filter(i=>i.status==="active");return a.length?a[a.length-1]:null}
function directUtility(x){const n=norm(x);if(/^(qué hora es|que hora es|hora|dime la hora|qué hora|que hora)[?.! ]*$/.test(n))return`Son las ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}.`;if(/^(qué fecha es|que fecha es|fecha|qué día es|que dia es|qué día|que dia)[?.! ]*$/.test(n))return`Hoy es ${new Date().toLocaleDateString([], {weekday:'long',year:'numeric',month:'long',day:'numeric'})}.`;const mm=x.match(/(?:calcula|cuanto es|cuánto es|resuelve)\s+([0-9\s+\-*/%^().]+)/i);if(mm){try{const e=mm[1].replace(/\^/g,"**");if(!/^[0-9+\-*/%*().\s]+$/.test(e))throw 0;const v=Function('"use strict";return ('+e+')')();if(!Number.isFinite(v))throw 0;return`El resultado es ${v}.`}catch{return"No pude verificar esa expresión con seguridad."}}return null}
function commonReply(x){const n=norm(x);const utility=directUtility(x);if(utility)return utility;const m=memory(x)[0],focus=activeIntent()?.text||S.presence.focus||null;if(/^(hola|hola grafito|hey|buenas|buenos dias|buenos días|buenas tardes|buenas noches)[!,. ]*$/.test(n))return"Hola. Estoy aquí.";if(/^(gracias|muchas gracias|vale gracias|ok gracias)[!,. ]*$/.test(n))return"De nada.";if(/^(ok|vale|bien|perfecto|listo|entiendo)[!,. ]*$/.test(n))return"Entendido.";if(/\b(cómo estás|como estas)\b/.test(n))return"Estoy activo y atento. Podemos seguir.";if(/\b(qué haces|que haces|qué estás haciendo|que estas haciendo)\b/.test(n))return focus?`Estoy siguiendo “${safeVisible(focus)}” y manteniendo lo pendiente sin dar nada por terminado antes de verificarlo.`:"Estoy atento a lo que me digas y manteniendo el contexto de esta conversación.";if(/\b(qué eres|que eres|quién eres|quien eres)\b/.test(n))return"Soy Grafito. Mantengo una identidad y memoria propias en este entorno; mis herramientas pueden cambiar, pero no sustituyen esa continuidad.";if(/\b(qué recuerdas|que recuerdas|recuerdas esto|memoria)\b/.test(n)){if(!m)return"No encuentro todavía un recuerdo relacionado con suficiente claridad. Prefiero decírtelo antes que inventarlo.";return`Sí. Lo más relacionado que recuerdo es: “${safeVisible(m.content)}”.`};if(/\b(continúa|continua|sigue|piensa|explora)\b/.test(n))return focus?`Sigo con “${safeVisible(focus)}”. Mantendré abiertas varias rutas y descartaré las que no pueda sostener con evidencia.`:"Sigo. Mantendré abiertas varias posibilidades y no trataré una suposición como si fuera un hecho.";if(/\b(quiero|necesito|mi objetivo|vamos a|haz|crea|diseña|construye|investiga|resuelve|ayúdame|ayudame)\b/.test(n))return"Sí. Lo tomo como objetivo y conservaré el contexto mientras avanzamos. No lo daré por hecho hasta tener un resultado verificable.";if(/[?¿]/.test(x)||/^(qué|que|cómo|como|por qué|por que|quién|quien|dónde|donde|cuándo|cuando|explica|puedes)/.test(n)){if(m)return`Recuerdo algo relacionado: “${safeVisible(m.content)}”. Lo usaré solo como contexto; si falta información para responder con seguridad, no la inventaré.`;return"Todavía no tengo una respuesta fiable guardada localmente para eso. Puedo seguir con el contexto que tenemos, pero no voy a inventar un dato que no pueda sostener."}return"Entiendo."}
function isIntent(x){return /\b(quiero|necesito|mi objetivo|vamos a|haz|crea|diseña|construye|investiga|resuelve|ayúdame|ayudame)\b/i.test(x)}
function sensitive(x){return /\b(dinero|banco|transfer|comprar|pagar|publicar|borrar|eliminar archivos|tercero)\b/i.test(x)}
function gapFor(x){const n=norm(x),a=[];for(const [q,l] of [["internet","internet en tiempo real"],["whatsapp","WhatsApp"],["gmail","Gmail"],["correo","correo externo"],["ubicacion","ubicación/GPS"],["ubicación","ubicación/GPS"],["camara","cámara"],["cámara","cámara"],["microfono","micrófono"],["micrófono","micrófono"],["banco","banca externa"],["api","API externa"]])if(n.includes(q))a.push(l);return[...new Set(a)]}
function addGap(capability,request){const e=S.gaps.find(g=>g.capability===capability&&g.status==="open");if(e){e.lastSeen=now();return}S.gaps.push({id:uid(),at:now(),lastSeen:now(),capability,request:clean(request),status:"open"});S.gaps=S.gaps.slice(-180)}
function addIntent(text,pid){const n=norm(text),old=S.intentions.find(i=>i.status==="active"&&norm(i.text)===n);if(old)return old;const i={id:uid(),createdAt:now(),text:clean(text,1000),status:"active",sourcePhotonId:pid,evidence:[]};S.intentions.push(i);S.intentions=S.intentions.slice(-160);S.plans.push({id:uid(),createdAt:now(),intentId:i.id,status:"active",steps:[{name:"definir evidencia y límites",status:"open"},{name:"comparar rutas",status:"open"},{name:"probar una acción verificable",status:"open"}]});S.plans=S.plans.slice(-160);return i}
async function remember(kind,content,opt={}){const visible=unwrap(content);if(!visible)return null;const fp=await hash(kind+"|"+(opt.status||"observed")+"|"+norm(visible)),recent=S.photon.nodes.slice(-220),e=recent.find(n=>n.fp===fp);if(e){e.hits=(e.hits||1)+1;e.lastSeen=now();return e}const n={id:uid(),at:now(),lastSeen:now(),kind,content:visible,status:opt.status||"observed",provenance:opt.provenance||"owner-input",fp,hits:1};S.photon.nodes.push(n);S.photon.nodes=S.photon.nodes.slice(-700);return n}
async function routes(seed){const h=await hash(seed),a=[];for(let i=0;i<5;i++){const p=parseInt(h.slice(i*8,i*8+8),16)>>>0;const q=parseInt(h.slice(40-i*4,48-i*4),16)>>>0;a.push(((p%86000)*1000000+(q%1000000)).toString())}S.q.routes=a;return a}
function addContra(subject){const s=clean(subject,500);if(S.world.contradictions.slice(-30).some(c=>c.subject===s&&c.status==="open"))return;S.world.contradictions.push({id:uid(),at:now(),subject:s,challenge:"¿Qué observación podría volver falsa o incompleta esta interpretación?",status:"open"});S.world.contradictions=S.world.contradictions.slice(-180)}
async function backgroundIntegrate(x,a){ident("perception",{kind:"text"});const p=await remember("perception",x);S.world.items.push({id:uid(),at:now(),content:clean(x,2500),status:"observed",provenance:"owner-input"});S.world.items=S.world.items.slice(-400);S.conversation.push({id:uid(),at:now(),role:"user",content:clean(x,2500),photonId:p?.id||null});if(isIntent(x)){const i=addIntent(x,p?.id||null);S.presence.focus=i.text}if(sensitive(x))S.ledger.push({id:uid(),at:now(),action:"sensitive-request",status:"blocked-pending-fresh-authorization",meta:{request:clean(x)}});for(const g of gapFor(x))addGap(g,x);await routes(x);addContra(x);S.conversation.push({id:uid(),at:now(),role:"assistant",content:safeVisible(a),engine:"universal-instant"});S.conversation=S.conversation.slice(-100);await remember("response",a,{status:"inferred",provenance:"language:universal-instant"});S.engine={kind:"universal-instant",status:"ready"};await save()}
function queueBackground(x,a){bg=bg.then(()=>backgroundIntegrate(x,a)).catch(e=>{S&&S.ledger.push({id:uid(),at:now(),action:"background-error",status:"failed",meta:{error:String(e).slice(0,200)}});scheduleSave(200)})}
function wake(){S.awake=true;S.presence.mode="awake";ident("wake");mode("awake");show("Sí.");queueBackground("Iter","Sí.");autonomy()}
function sleep(){S.awake=false;S.presence.mode="sleep";ident("sleep");mode("sleep");show("");scheduleSave()}
function send(){const x=entry.value.trim();if(!x)return;entry.value="";const n=norm(x);if(n==="iter"){if(!S.awake)wake();else show("Sí.");return}if(!S.awake){show("");return}if(n==="duerme"||n==="detente"){sleep();return}const a=commonReply(x);show(a);mode("awake");queueBackground(x,a)}
function autonomy(){clearInterval(T);T=setInterval(()=>{if(!S?.awake||document.hidden)return;S.lastTickAt=now();S.q.cycles=(S.q.cycles||0)+1;ident("cognitive-tick",{reason:"visible-runtime",cycle:S.q.cycles});const i=activeIntent();if(i)S.presence.focus=i.text;scheduleSave(120)},120000)}
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&S?.awake){S.lastTickAt=now();ident("resume");scheduleSave(120)}});
async function unlock(){err.textContent="";const secret=key.value;if(!secret)return;if(await hash(SALT+secret)!==EXPECTED){err.textContent="Clave incorrecta.";key.value="";return}try{K=await deriveKey(secret);await load();lock.style.display="none";key.value="";mode(S.awake?"awake":"sleep");if(S.awake)autonomy();entry.focus()}catch(e){console.error(e);err.textContent="No pude abrir el estado cifrado en este navegador."}}
entry.addEventListener("keydown",e=>{if(e.key==="Enter")send()});$("#unlock").addEventListener("click",unlock);key.addEventListener("keydown",e=>{if(e.key==="Enter")unlock()});mode("sleep");
